# Generated by Django 4.1.3 on 2022-12-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30)),
                ('car_company', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=20)),
                ('car_price', models.IntegerField()),
            ],
        ),
    ]
