# Generated by Django 4.1.3 on 2022-12-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_price',
            new_name='total_model_of_cars',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
    ]
